### ISSUE TITLE
Dispatching an action when the widget is init.

### ISSUE THREAD

**Issue by WenhaoWu** [hemanthrajv/fludex#1]
Is there anyway to dispatch the actions when the widget is init? 

eg. Calling `_delayedAction(context)` on the second example in the build method before returns. I tried but it throws error regarding 

>setState() or markNeedsBuild() called during build.

**Comment by hemanthrajv** [comment]
Dispatching actions in build method before return works great for me.

And moreover, calling an action with context as payload before return in build method is not advisable, as sometimes the dispatched action might resolve even before the widget(that uses the state) is built.

Would be helpful if you could share some code.

**Comment by WenhaoWu** [comment]
Thanks for the quick responding. I think dispatching action with context in payload was the problem.

BTW, I somehow notice there will be more than one time of action dispatching if we simply do it before return, just like below:

```
@override
 Widget build(BuildContext context) {

    _change();

    return new Scaffold(
      ...
    );
  }
``` 

Below is the logger
>I/flutter (30427): [INFO] Fludex Logger: {
I/flutter (30427):   Action: CHANGE,
I/flutter (30427):   Previous State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 5, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Next State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 6, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Timestamp: 2017-11-23 15:46:56.662539
I/flutter (30427): }
I/flutter (30427): [INFO] Fludex Logger: {
I/flutter (30427):   Action: CHANGE,
I/flutter (30427):   Previous State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 6, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Next State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 7, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Timestamp: 2017-11-23 15:46:56.744499
I/flutter (30427): }
I/flutter (30427): [INFO] Fludex Logger: {
I/flutter (30427):   Action: CHANGE,
I/flutter (30427):   Previous State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 7, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Next State: {HomeScreen: 0, SecondScreen: {state: Refreshed, count: 8, status: FutureAction yet to be dispatched, loading: false}},
I/flutter (30427):   Timestamp: 2017-11-23 15:46:56.963122
I/flutter (30427): }

Look at the timestamp.

**Comment by hemanthrajv** [comment]
Not sure if it is due to the lib or actions dispatched before return.

without adding any action before return statement but a `debugPrint("build called")` has similar result.

example: 

```dart
Widget build(BuildContext context){
    debugPrint("build called");
...
...
```

Wil look into.

**Comment by hemanthrajv** [comment]
Don't know why that happens, but changing 

this:
```dart
// Run app
  runApp(new MaterialApp(
    home: new HomeScreen(),
    routes: <String, WidgetBuilder>{
      HomeScreen.name: (BuildContext context) => new HomeScreen(),
      SecondScreen.name: (BuildContext context) => new SecondScreen()
    },
  ));
```

to:
```dart
  HomeScreen _homeScreen = new HomeScreen();
  SecondScreen _secondScreen = new SecondScreen();

  // Run app
  runApp(new MaterialApp(
    home: _homeScreen,
    routes: <String, WidgetBuilder>{
      HomeScreen.name: (BuildContext context) => _homeScreen,
      SecondScreen.name: (BuildContext context) => _secondScreen
    },
  ));
```
fixes the issue of build being called multiple times.
